name: Python linting
on: [push, pull_request]
concurrency:
  group: py-lint-${{ github.ref }}
  cancel-in-progress: true
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.6', '3.9']
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Cache pip dir
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: pip-cache-${{ matrix.python-version }}-${{ hashFiles('lib/galaxy/dependencies/pinned-lint-requirements.txt') }}
      - name: Install tox
        run: pip install tox
      - name: Run linting
        run: tox -e lint
      - name: Run docstring linting
        run: tox -e lint_docstring_include_list
      - name: Run mypy checks
        run: tox -e mypy
